#!/usr/bin/python

import os, sys
import argparse
import logging
import json

netmripath=os.path.abspath('../python-netmriconn')
sys.path.append(netmripath)
import netmriconn

ibpath=os.path.abspath('../python-ibconn')
sys.path.append(ibpath)
import ibconn

def main():

    parser = argparse.ArgumentParser(description='Find information about dhcp leases',
                                     formatter_class=argparse.RawDescriptionHelpFormatter,
                                     epilog='''
Example: getmac -m AA:BB:CC:11:22:33'''
                                     )
    
    parser.add_argument('--loglevel', dest='loglevel', type=str,
                        choices = ['DEBUG','INFO','WARNING','ERROR', 'CRITICAL'],
                        default = 'WARNING',
                        help='set logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)')
    parser.add_argument('-m', '--mac', dest='macaddr', type=str,
                        help='end host mac address')
    parser.add_argument('-ibconf', dest='ibconf', type=str,
                        help='infoblox library config file path',
                        default = 'ib.cfg')
    args = parser.parse_args()
    if not (args.macaddr):
        parser.error('No mac address provided, -m is required')

    macaddr = args.macaddr
    ibconf = args.ibconf
    loglevel = args.loglevel

    if loglevel == 'DEBUG':
        logging.basicConfig(level=logging.DEBUG)

    ib = ibconn.ibconn(ibconf)

    r = ib.get_macfilteraddress('mac', macaddr, 10)
    json.dumps(r, separators=(',',':'), sort_keys=True, indent=4)

if __name__ == '__main__':
    sys.exit(main())
